name: Deploy to ConoHa WING

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy static site by FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.CONOHA_FTP_SERVER }}
          username: ${{ secrets.CONOHA_FTP_USERNAME }}
          password: ${{ secrets.CONOHA_FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.CONOHA_FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/output/**
            **/section-images/**
